### ISSUE TITLE
Terraform 0.12 support, changelog from fork pending

### ISSUE THREAD

**Issue by pgold30** [sumup-oss/terraform-provider-vaulted#2]
https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers/
Is there a plan / estimated date to move this to terraform 0.12? what is the estimated date?

And also implement the changelog under https://github.com/hashicorp/vault/blob/master/CHANGELOG.md , in which version do we created this fork?

**Comment by phazer69** [comment]
Hi @pgold30, 
We have just released a version with the updated terraform SDK with compatibility for terraform sdk 0.12.16

**Comment by pgold30** [comment]
Hi @phazer69  thanks for this, can you please share from which version u forked https://github.com/hashicorp/vault  and if you plan to implement the changelog since that version ?

**Comment by pgold30** [comment]
@phazer69  Can u also make giithub.com:sumup/terraform_mod_vault comaptible with 0.12? . 
Also this release is not backwards compatible right? We call both to provision vault im getting the error ```Error: Failed to instantiate provider "vaulted" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]```
